# Testing on trained model

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
plt.style.use('ggplot')

import nltk

In [2]:
df = pd.read_csv('Product_review.csv')
print(df.shape)
df = df.iloc[200000:300000]
print(df.shape)

(982619, 10)
(100000, 10)

In [3]:
df.head()

,Unnamed: 0,asin,helpful,overall,reviewText,reviewTime,reviewerID,reviewerName,summary,unixReviewTime
200000,200000,B007P56NBS,"[0, 0]",4,"This was a fun, fast read. While there was a ...","04 17, 2012",A1UDJWL74M5170,"Jess ""The Romanceaholic""","A Fun, Fast, Romantic Read",1334620800
200001,200001,B007P56NBS,"[0, 0]",5,This is a great book! Cole is a sharp business...,"06 25, 2014",AER3NZ1H79LGZ,Laura Collins,Great Book!!,1403654400
200002,200002,B007P56NBS,"[0, 0]",5,"Maggie Marr delivers a superbly written, fun a...","06 29, 2012",A2949WD37L7G1Z,Lovestoread,"Fun, emotional and sexy",1340928000
200003,200003,B007P56NBS,"[0, 0]",3,"Entertaining, easy to read, it's the perfect k...","04 2, 2012",A16FOH38QG1UFW,luciefuentes,Perfect beach book !,1333324800
200004,200004,B007P56NBS,"[0, 0]",4,First things first in this review: this one is...,"04 17, 2012",A2XJ8QIPLNP5NI,Rea,An enjoyable light romance,1334620800

In [4]:
test_data = df.drop(['asin','helpful','reviewTime','reviewerID','reviewerName','unixReviewTime','summary'],axis=1)

In [5]:
test_data

        Unnamed: 0  overall                                         reviewText
200000      200000        4  This was a fun, fast read.  While there was a ...
200001      200001        5  This is a great book! Cole is a sharp business...
200002      200002        5  Maggie Marr delivers a superbly written, fun a...
200003      200003        3  Entertaining, easy to read, it's the perfect k...
200004      200004        4  First things first in this review: this one is...
...            ...      ...                                                ...
299995      299995        5  I enjoyed walking my way through "Women of Str...
299996      299996        5  Kimberly Payne writes from the heart as well a...
299997      299997        5  I really like how the author laid out this boo...
299998      299998        5  I had backslidden on my exercising and had bee...
299999      299999        5  Women of Strengthwritten by Kimberley PayneBel...

[100000 rows x 3 columns]

In [6]:
test_data.rename(columns = {'Unnamed: 0':'ID','overall':'Ratings'}, inplace = True)

In [7]:
test_data

            ID  Ratings                                         reviewText
200000  200000        4  This was a fun, fast read.  While there was a ...
200001  200001        5  This is a great book! Cole is a sharp business...
200002  200002        5  Maggie Marr delivers a superbly written, fun a...
200003  200003        3  Entertaining, easy to read, it's the perfect k...
200004  200004        4  First things first in this review: this one is...
...        ...      ...                                                ...
299995  299995        5  I enjoyed walking my way through "Women of Str...
299996  299996        5  Kimberly Payne writes from the heart as well a...
299997  299997        5  I really like how the author laid out this boo...
299998  299998        5  I had backslidden on my exercising and had bee...
299999  299999        5  Women of Strengthwritten by Kimberley PayneBel...

[100000 rows x 3 columns]

In [8]:
test_data.isnull().sum()

ID            0
Ratings       0
reviewText    1
dtype: int64

In [9]:
test_data["reviewText"].fillna("No data", inplace = True)

In [10]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split

### Pre process the text of new date to give into model

In [11]:
cv = CountVectorizer(max_features=100)
X = test_data["reviewText"]
X = cv.fit_transform(X).toarray()

## Load the model for prediction

In [12]:
import joblib
classifire = joblib.load("random_forest_model")

In [13]:
y_pred = classifire.predict(X)

In [14]:
print(y_pred)

['positive' 'positive' 'positive' ... 'positive' 'positive' 'positive']

### Create another column of prediction

In [15]:
test_data["predicted_labels"] = y_pred.tolist()
test_data.head(10)

,ID,Ratings,reviewText,predicted_labels
200000,200000,4,"This was a fun, fast read. While there was a ...",positive
200001,200001,5,This is a great book! Cole is a sharp business...,positive
200002,200002,5,"Maggie Marr delivers a superbly written, fun a...",positive
200003,200003,3,"Entertaining, easy to read, it's the perfect k...",positive
200004,200004,4,First things first in this review: this one is...,positive
200005,200005,4,Posted on Romancing the Book's blogReviewed by...,positive
200006,200006,4,I enjoyed this book just as much as 'Hollywood...,positive
200007,200007,4,"My Review:This book is a fun, sweet, easy-to-r...",positive
200008,200008,4,"I got this book because, I thought it sounded ...",positive
200009,200009,5,Maggie Marr has delivered another steamy roman...,positive

In [16]:
test_data.tail(20)

,ID,Ratings,reviewText,predicted_labels
299980,299980,5,Find Emily is a top notch crime thriller featu...,positive
299981,299981,5,I love the way the author builds the trust and...,positive
299982,299982,5,My review of Baptism of Fire by Stephanie Cons...,positive
299983,299983,4,Ever Since Leito's mother was killed by a drag...,Negative
299984,299984,5,This book is made of amazing and reminds me wh...,positive
299985,299985,3,"When Leito's mother is killed by dragons, her ...",Negative
299986,299986,4,okay when i was asked if i would like to do a ...,positive
299987,299987,5,I honestly thought Baptism of Fire was a great...,positive
299988,299988,5,This story is rich in detail and flavor - and ...,positive
299989,299989,5,"I figured the plot out quickly,but that didn't...",positive
299990,299990,5,This was a veey good story the characters whe...,positive
299991,299991,4,I enjoyed the story. It had the mystery and th...,positive
299992,299992,5,these are great to read if you like books abou...,positive
299993,299993,2,The story was good and I enjoyed the character...,positive
299994,299994,3,"Good read but predictable. Glad I got it, glad...",positive
299995,299995,5,"I enjoyed walking my way through ""Women of Str...",positive
299996,299996,5,Kimberly Payne writes from the heart as well a...,positive
299997,299997,5,I really like how the author laid out this boo...,positive
299998,299998,5,I had backslidden on my exercising and had bee...,positive
299999,299999,5,Women of Strengthwritten by Kimberley PayneBel...,positive

In [17]:
import openpyxl
writer = pd.ExcelWriter("Tested reviews.xlsx")
test_data.to_excel(writer)
writer.save()
print("dsatframe is exported successfully and converted to excel")

dsatframe is exported successfully and converted to excel